# Generated by Django 4.2.11 on 2024-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sidebar',
            field=models.IntegerField(choices=[(0, 'Maximized'), (1, 'Minimized')], default=0, verbose_name='sidebar'),
        ),
    ]
